### PR TITLE
Feature: Limit billable bytes per query; Add estimated cost display

### PR DESCRIPTION
**Pull request by abannachGrafana**
## Problem

As an admin, I may want to control the cost of my query spend. With the BigQuery client this can be done by specifying the `MaxBytesBilled` on the `QueryConfig`. Also, I know what our on demand compute price is and would like to estimate the cost of running a query at validation time so that my users can conceptualize what their queries cost and consider optimizing them.

## Description

This PR adds two optional configuration fields to the datasource:

- `maxBillableBytes` : Applied to the queryconfig on the backend to prevent large queries from running
- `onDemandComputePrice`: Strictly used for display purposes on the frontend gives the user an approximate cost of running their query to 4 decimal places. Since the price is per terabyte 4 decimal places gives better visibility to smaller queries.

image

image
image

image

### CODE REVIEW

**Comment by duncan771** [comment]
This looks great @abannachGrafana! Would love to have this so we can continue cutting unnecessary BigQuery costs through Grafana BI.

Have y'all had a chance to look at this? @zoltanbedi, @yesoreyeram, @gabor

**Comment by gabor** [comment]
@abannachGrafana as we discussed, when you'll have time, please create a separate PR for the `maxBillableBytes` part, we can handle that first, and then we can discuss the `onDemandComputePrice` part. thanks!

**Comment by duncan771** [comment]
> @abannachGrafana as we discussed, when you'll have time, please create a separate PR for the `maxBillableBytes` part, we can handle that first, and then we can discuss the `onDemandComputePrice` part. thanks!

@gabor [here](https://github.com/grafana/google-bigquery-datasource/pull/254) is one of the new PRs that splits this. It should contain just the changes required for the `maxBillableBytes` feature to be added.

**Comment by ivanahuckova** [comment]
@abannachGrafana Thank you for your contribution. After consideration, we have decided not to proceed with the estimated cost display feature. We believe that the potential inaccuracies in calculation could provide users with a false sense of security.

The limit billable bytes per query feature has been merged. Thank you for contribution!

**Pull request closed without merging**
